### ISSUE TITLE
Hosting Problem

### ISSUE THREAD

**Issue by iimog** [AndrewIOM/gpp-cqrs#7]
Hi Andrew,

I came across your nice article in MEE and wanted to check out the website. Unfortunately it is currently not reachable. This is probably a problem with your hosting provider rather than the code.
The reported error is:

Error 502 - Bad gateway
Ray ID: 3db82e83ac402372 • 2018-01-11 13:21:53 UTC

I'm trying to connect from Germany.
Looking forward to trying the gpp.
Best regards,
Markus

**Comment by AndrewIOM** [comment]
Hi Markus

Sorry about this. I was having temporary issues with Azure, which have now thankfully been resolved. Hope you enjoy the site.

Thanks
Andy

**Comment by iimog** [comment]
Thank you very much. The site looks amazing.
